apiVersion: v1
kind: Pod
metadata:
  name: mon-application
  labels:
    app: my-app
spec:
  containers:
  - name: backend-container
    image: anouarelanda/monapp-nodejs:v1.1
    ports:
    - containerPort: 3000

  - name: frontend
    image: anouarelanda/monapp-react:latest
    ports:
    - containerPort: 5000

  restartPolicy: Always
