apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
      - name: init-db
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: backend-container
        image: anouarelanda/monapp-nodejs:v1.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"  # Demande 250 milli-cores de CPU
            memory: "128Mi"  # Demande 128 MiB de mémoire
          limits:
            cpu: "500m"  # Limite à 500 milli-cores de CPU
            memory: "256Mi"  # Limite à 256 MiB de mémoire
      - name: frontend
        image: anouarelanda/monapp-react:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "250m"  # Demande 250 milli-cores de CPU
            memory: "128Mi"  # Demande 128 MiB de mémoire
          limits:
            cpu: "500m"  # Limite à 500 milli-cores de CPU
            memory: "256Mi"  # Limite à 256 MiB de mémoire
