apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: my-mysql
spec:
  containers:
  - name: mysql-container
    image: anouarelanda/mysql:8.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "secret"
    - name: MYSQL_DATABASE
      value: "user_microservice"
