apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      containers:
      - name: mysql-container
        image: anouarelanda/mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret"
        - name: MYSQL_DATABASE
          value: "user_microservice"
        resources:
          requests:
            cpu: "500m"  # Demande 500 milli-cores de CPU
            memory: "512Mi"  # Demande 512 MiB de mémoire
          limits:
            cpu: "1000m"  # Limite à 1000 milli-cores de CPU
            memory: "1024Mi"  # Limite à 1024 MiB de mémoire
