apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1  # Adjust later if needed
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: backend
          image: anouarelanda/monapp-nodejs:v1.1
          ports:
            - containerPort: 3000  # port your backend app listens on
      
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80  # Exposed port for accessing the Node.js app
      targetPort: 3000  # PortNode.js app is listening on
  type: LoadBalancer  # Type 
