apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3  # Adjust as per your need
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image:   # Docker image
          ports:
            - containerPort: 3000  # Adjust if Node.js app listens on diff port
          env:
            - name: DATABASE_URL
              value: #mysql://username:password@mysql-service:3306/db_name  # Replace with your MySQL connection details
            # Other environment variables needed for your Node.js app

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 8080  # Exposed port for accessing the Node.js app
      targetPort: 3000  # Port Node.js app is listening on
  type: LoadBalancer  # Type can be adjusted
