apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30008  
      targetPort: 5000
  type: NodePort
