# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# Fit will also deploy the containerized app (docker) to kubernetes

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    #Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t notchai/ecamazon_users:latest .

    - name: Push Docker image to registry
      run: docker push notchai/ecamazon_users:latest

    #Kubernetes
    - name: Deploy to Kubernetes
      run: |
          kubectl apply -f kube.yml
          

  
